-- =========================================================
-- OATec 2026 - Supabase schema + RLS corregido
-- Ejecutar TODO este script en SQL Editor de Supabase
-- =========================================================

-- Extensión opcional para UUID si luego la necesitás
create extension if not exists pgcrypto;

-- Tabla principal
create table if not exists public.inscripciones_oatec (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  first_name text not null,
  last_name text not null,
  age integer not null check (age between 12 and 21),
  birth_date date not null,
  dni varchar(8) not null,
  course varchar(2) not null check (course in ('4','5','6','7')),
  division varchar(1) not null check (division in ('A','B','C')),
  institution text not null default 'Instituto San Miguel',
  competition text not null default 'OATec ITBA 2026',
  theme text not null default 'Desafío Espacial',
  submitted_at_iso text,
  source text not null default 'github-pages',
  status text not null default 'pendiente' check (status in ('pendiente','aprobado','rechazado'))
);

-- Índices útiles
create index if not exists inscripciones_oatec_created_at_idx
  on public.inscripciones_oatec (created_at desc);

create index if not exists inscripciones_oatec_dni_idx
  on public.inscripciones_oatec (dni);

create index if not exists inscripciones_oatec_status_idx
  on public.inscripciones_oatec (status);

-- Evita duplicados por DNI si querés permitir solo una inscripción por alumno
-- Si no querés esta regla, comentá la línea siguiente
create unique index if not exists inscripciones_oatec_dni_unique
  on public.inscripciones_oatec (dni);

-- Habilitar RLS
alter table public.inscripciones_oatec enable row level security;

-- Limpiar políticas previas para evitar conflictos
drop policy if exists "Public can insert inscriptions" on public.inscripciones_oatec;
drop policy if exists "Anon can insert inscriptions" on public.inscripciones_oatec;
drop policy if exists "Anyone can insert inscriptions" on public.inscripciones_oatec;
drop policy if exists "Admins can read inscriptions" on public.inscripciones_oatec;
drop policy if exists "Admins can update inscriptions" on public.inscripciones_oatec;
drop policy if exists "Admins can delete inscriptions" on public.inscripciones_oatec;
drop policy if exists "Authenticated admins can read inscriptions" on public.inscripciones_oatec;
drop policy if exists "Authenticated admins can update inscriptions" on public.inscripciones_oatec;
drop policy if exists "Authenticated admins can delete inscriptions" on public.inscripciones_oatec;

-- =========================================================
-- POLÍTICA CLAVE:
-- permite insertar desde el formulario público usando anon key
-- =========================================================
create policy "Anon can insert inscriptions"
on public.inscripciones_oatec
for insert
to anon
with check (true);

-- Panel admin: lectura / edición / borrado sólo para el usuario admin
-- creado en Supabase Auth con email admin@oatec.local
create policy "Authenticated admins can read inscriptions"
on public.inscripciones_oatec
for select
to authenticated
using ((auth.jwt() ->> 'email') = 'admin@oatec.local');

create policy "Authenticated admins can update inscriptions"
on public.inscripciones_oatec
for update
to authenticated
using ((auth.jwt() ->> 'email') = 'admin@oatec.local')
with check ((auth.jwt() ->> 'email') = 'admin@oatec.local');

create policy "Authenticated admins can delete inscriptions"
on public.inscripciones_oatec
for delete
to authenticated
using ((auth.jwt() ->> 'email') = 'admin@oatec.local');

-- Permisos a nivel SQL
grant usage on schema public to anon, authenticated;
grant insert on public.inscripciones_oatec to anon;
grant select, update, delete on public.inscripciones_oatec to authenticated;

-- Si la columna identity requiere secuencia, esto evita problemas de permisos
grant usage, select on all sequences in schema public to anon, authenticated;

-- =========================================================
-- OPCIONAL: verificación rápida
-- =========================================================
-- select * from public.inscripciones_oatec order by created_at desc;
